FROM ignitehq/cli@sha256:3a95f6762a8ede6903a16694e7775c98850236f5166c9a88d6dc26700a9bc6e9 AS base

COPY --chown=tendermint:tendermint wormchain /apps/wormchain
COPY --chown=tendermint:tendermint sdk /apps/sdk

WORKDIR /apps/wormchain

FROM base AS ignite-go-build
RUN ignite generate proto-go

FROM scratch AS go-export
COPY --from=ignite-go-build /apps/wormchain/x/wormhole/types /x/wormhole/types
COPY --from=ignite-go-build /apps/wormchain/x/tokenfactory/types /x/tokenfactory/types
COPY --from=ignite-go-build /apps/wormchain/x/ibc-composability-mw/types /x/ibc-composability-mw/types

FROM base AS ignite-vue-build
RUN NODE_OPTIONS="" ignite generate vuex --proto-all-modules

FROM scratch AS vue-export
COPY --from=ignite-vue-build /apps/wormchain/vue/ /vue
