FROM ignitehq/cli@sha256:e5cbd8374d506950312f9c4e6f1ab003c7ed40c095b14e2293aec42343a44823 AS base

COPY --chown=tendermint:tendermint wormchain /apps/wormchain
COPY --chown=tendermint:tendermint sdk /apps/sdk

WORKDIR /apps/wormchain

FROM base AS ignite-go-build
RUN ignite generate proto-go

FROM scratch AS go-export
COPY --from=ignite-go-build /apps/wormchain/x/wormhole/types /x/wormhole/types
COPY --from=ignite-go-build /apps/wormchain/x/tokenfactory/types /x/tokenfactory/types
COPY --from=ignite-go-build /apps/wormchain/x/ibc-composability-mw/types /x/ibc-composability-mw/types

FROM base AS ignite-vue-build
RUN NODE_OPTIONS="" ignite generate vuex --proto-all-modules

FROM scratch AS vue-export
COPY --from=ignite-vue-build /apps/wormchain/vue/ /vue
